### ISSUE TITLE
Does not appear to be working when using JsonApiAdapter

### ISSUE THREAD

**Issue by jackmatt2** [mdehoog/ember-data-has-many-query#11]
Here is the setup:

    //adapters/sso-application.js
    export default JSONAPIAdapter.extend(HasManyQuery.RESTAdapterMixin, {
       ...
    });

    //models/sso-application.js
    export default DS.Model.extend(HasManyQuery.ModelMixin, {
       ...
       userTypeSubscriptions: hasMany(),
    });

Execute a query from an sso-application model as follows:

     model.query('userTypeSubscriptions', { institutionOrganisation: "100"});

Produces the following request

    GET /rest/sso-applications/100

Should it not be doing

    GET /rest/sso-applications/2/userTypeSubscriptions?institutionOrganisation=100

Maybe I am doing something wrong.

![image](https://cloud.githubusercontent.com/assets/6348088/15279568/0fc9b442-1b69-11e6-8721-7bf47c24c931.png)

**Comment by mdehoog** [comment]
Thanks for the debugging screenshot. Any chance of doing a similar thing with the addon's `rest-adapter` mixin in the `findHasMany` and `buildRelationshipQuery` functions?

**Comment by jackmatt2** [comment]
Ah, that will be difficult actually because this is a pretty large app.  I debug a particular method if that would help.

**Comment by mdehoog** [comment]
Sorry that's what I mean, put breakpoints in the `rest-adapter.js` mixin's `findHasMany` and `buildRelationshipQuery` functions and step through.

**Comment by jackmatt2** [comment]
Ah I see, I thought you meant change the app to use DS.RestAdapter, will do this now.

**Comment by jackmatt2** [comment]
Added `debugger;` statements to both those methods but they are never hit.

**Comment by jackmatt2** [comment]
`ember-data@^2.4.0`, I can add debug statements elsewhere also, just let me know.

**Comment by jackmatt2** [comment]
Can confirm that the methods are being hit at other routes such as:

```
  afterModel(model) {
    return model.get('ssoApplications').reload();
  }
```

But that is using the `get` function not the `query` function.

**Comment by mdehoog** [comment]
In version `0.1.0` I switched the relationship reloading to use the new `ds-references` feature in ember-data `2.5`. You could either try updating your ember-data version, or switching back to an older version of this addon: `0.0.6`.

**Comment by jackmatt2** [comment]
I updated to 2.5.3 but am still having this issue, the debug points in the mixin are never hit.  I can see it hitting the 'reload' function in the adapter but no reference to this addon. 

    "ember-data": "2.5.3",
    "ember-data-has-many-query": "0.1.1",


![image](https://cloud.githubusercontent.com/assets/6348088/15344432/2f99b600-1cea-11e6-91ee-36620816653e.png)

**Comment by mdehoog** [comment]
Is it hitting `findHasMany` in the adapter? Here is my call-stack for reference:

<img width="991" alt="screen shot 2016-05-18 at 11 46 55 am" src="https://cloud.githubusercontent.com/assets/1538523/15344950/44224d0e-1cee-11e6-8ef0-96042967d595.png">

**Comment by jackmatt2** [comment]
No, it is never called.

**Comment by jackmatt2** [comment]
![image](https://cloud.githubusercontent.com/assets/6348088/15345300/21ff7aa0-1cf1-11e6-9b8d-8b3d3f3483de.png)

**Comment by mdehoog** [comment]
How about the `store.js` `findHasMany`?

**Comment by jackmatt2** [comment]
also never called

**Comment by jackmatt2** [comment]
Gets to the reload

![image](https://cloud.githubusercontent.com/assets/6348088/15345513/19ee5df2-1cf3-11e6-9a08-6662cca6e842.png)

Then

![image](https://cloud.githubusercontent.com/assets/6348088/15345538/3634d16c-1cf3-11e6-997c-5c53e6e591ab.png)

Then

![image](https://cloud.githubusercontent.com/assets/6348088/15345557/51ea812c-1cf3-11e6-97f3-cb8e98c8aa8d.png)

Then is schedules the fetch but fetches is an empty array ... not sure if this is right.

![image](https://cloud.githubusercontent.com/assets/6348088/15345623/ceaed334-1cf3-11e6-8be1-29b6535bd6bf.png)

**Comment by mdehoog** [comment]
It looks like your payload for the parent record doesn't provide a `link` attribute for the hasMany relationship records, which is required for the adapter to know which URL to hit to request the child records.

I'm guessing that a `get` on `userTypeSubscriptions` returns an empty array also. 

The payload for sso-application should contain a `links` attribute, for example:

```json
links: {
    "userTypeSubscriptions": "userTypeSubscriptions"
}
```
 Your `hasMany` should be marked as `async: true`. I would suggest getting `get` to work (return all records) before moving on to filtering using `query`. A `get` should hit:
```
GET /rest/sso-applications/2/userTypeSubscriptions
```

**Comment by jackmatt2** [comment]
I am using ember-cli-mirage (latest version with Models) right now and can confirm that it is producing the following in the relationships hash.

![image](https://cloud.githubusercontent.com/assets/6348088/15346794/a4c461c8-1cfe-11e6-8b86-49647e9c3864.png)

So you are correct.  I will try to figure out how to get this working properly in mirage.

**Comment by jackmatt2** [comment]
This is working in a live environment where the JSON responses are correctly formatted.  Thanks for the help.

**Comment by rstudner** [comment]
if using a JSONAPIAdapter:
when I do:
order.query('orderItems', {'order_id': 2101384});

shouldn't that url be something like:
/api/orders/:id/order-items?filter[order_id]=2101384

right now this produces ?order_id=2101384
