### ISSUE TITLE
HasManyQuery.RESTAdapterMixin - causing delete to no longer work.

### ISSUE THREAD

**Issue by jackmatt2** [mdehoog/ember-data-has-many-query#13]
ember-data@2.5.3
ember-data-has-many-query@0.1.0

It appears that when destroying a record that has the `HasManyQuery.RESTAdapterMixin` in the adapter, it caused the following error to occur with the JSONAPIAdapter.

`Cannot set property 'jqXHR' of undefined`

See [this](http://stackoverflow.com/questions/37404518/getting-error-when-trying-to-delete-record-from-hasmany-collection) stackoverflow quesion

After removing the Mixin from the adapter, everything is working again.

**Comment by mdehoog** [comment]
Thanks for the bug report, this should have been fixed in `v0.1.1`, please try updating to the latest version. Let me know if it is still an issue.

**Comment by jackmatt2** [comment]
Yes updating worked.
