### ISSUE TITLE
Not triggering change in view

### ISSUE THREAD

**Issue by jeroenhouben** [mdehoog/ember-data-has-many-query#14]
Disclaimer: i'm pretty new to Ember

I'm trying your plugin, which I was suprised to see is not part of Ember Data. This is a very common usecase right? Anyway, it's working on the data end, but not updating the view.

I've got a component, and with this code I get a list of translations:

```
  didReceiveAttrs() {
    this._super(...arguments);
    this.set('translations', this.get('project').get('translations'));
  }
```

But with this code I don;t see them. The query is executed and results are returned, same ones as above, but nothing gets rendered.. Any ideas?

```
  didReceiveAttrs() {
    this._super(...arguments);
    this.set('translations', this.get('project').query('translations', {}));
  }
```

The translations are loaded in the store:

![image](https://cloud.githubusercontent.com/assets/10760/16594919/ec354d42-42ec-11e6-8215-677f300a982b.png)

**Comment by jeroenhouben** [comment]
Hmm this seems to work:

```
  didReceiveAttrs() {
    this._super(...arguments);

    let that = this;
    this.get('project').query('translations',{}).then(function (translations) {
      that.set('translations', translations);
    })
  }
```

**Comment by mdehoog** [comment]
The value returned from the `query` function is an `RSVP.Promise`, and Ember views don't update when a promise is resolved (see http://stackoverflow.com/questions/21496761/promise-value-not-put-into-template-after-resolved). Normally you use `query` in a route's `model` function, and return the promise, which means the promise is resolved before the view is rendered.

Your solution is one way of doing it. The other way is mentioned in the link above:
```
    this.set('translations', Ember.ObjectProxy.extend(Ember.PromiseProxyMixin).create({
        promise: this.get('project').query('translations', {})
    }));
```

The translations should then be available in the `translations.value` property once the promise is resolved. (NB I have not tested this.)
