### ISSUE TITLE
Sticky belongs-to doesn't work

### ISSUE THREAD

**Issue by danilovaz** [mdehoog/ember-data-has-many-query#17]
Thank's for this amazing addon. 

I'm using:
```
Ember             : 2.9.0
Ember Data        : 2.9.0
jQuery            : 3.1.1
Ember Simple Auth : 1.1.0
```

I'm have problems with `Sticky belongs-to`. My project has model `chat` and model `chatMessage`. `chat` `hasMany` `chaMessages` and `chatMessages` `belongsTo` `chat`.

**model chat.js**
```js
import Model from 'ember-data/model';
import attr from 'ember-data/attr';
import { belongsTo, hasMany } from 'ember-data/relationships';
import HasManyQuery from 'ember-data-has-many-query';

export default Model.extend(HasManyQuery.ModelMixin,{
  name: attr('string'),
  date: attr('date'),
  chatMessages: hasMany('chat-message', { async: true })
});
```

**model chatMessage.js**
```js
import Model from 'ember-data/model';
import attr from 'ember-data/attr';
//import emojione from 'emojione';
import { belongsTo, hasMany } from 'ember-data/relationships';
import HasManyQuery from 'ember-data-has-many-query';

export default Model.extend(HasManyQuery.ModelMixin,{
  message: attr('string'),
  date: attr('date'),
  chat: HasManyQuery.belongsToSticky('chat')
});
```
I'm implementing an action like "Read More" to get more items from `chatMessages`. My API expect a request with params:
`https://myapi.com/chats/2/chat-messages?page%5Bnumber%5D=1475591389&page%limit%5D=20`

**Route** `chats/show`: `https://myapi.com/chats/2/chat-messages`
```js
model(params) {
    return Ember.RSVP.hash({
      chat: this.store.findRecord('chat', params.chat_id)
    })
}
```
In this pieace of code above, I'm get the `chat` user has selected: `https://myapi.com/chats/2/chat-messages` and because I'm using `JSONAPI` this already push `chatMessages` in store.

So when user click in action "readMore" I'm doing this:
```js
actions: {
    readMore(chatId, pageNumber) {
      this._super(...arguments);
      let chat = this.controller.get('model.chat');

      this.set('chat-messages', Ember.ObjectProxy.extend(Ember.PromiseProxyMixin).create({
        promise: this.controller.get('model.chat').query('chatMessages', { page: { number: pageNumber } })
      }));
   }
}
```
With this, I'm capable to get items from `https://myapi.com/chats/2/chat-messages?page%5Bnumber%5D=1475591389&page%limit%5D=20` BUT :sob: it's clear the frist 20 items I'm already get in: `https://myapi.com/chats/2/chat-messages`

How can I persist this data? I'm following `Sticky belongs-to` but it's doesn't work. Please, you can help with this? Have any idea?

Thanks!

**Comment by mdehoog** [comment]
Apologies, the README on this is a bit unclear. When you query the API to get the next page, the hasMany relationship is cleared and the new data is loaded. This is because `query` calls `reload` on the hasMany relationship, which clears and reloads the data.

The way I implemented `readMore` functionality in my app was to store the records in a separate array. For example, in the component, have a messages property which is an array, and each time you load another page push the loaded records into this array:

```javascript
  readMore: function(page) {
    var self = this;
    this.get('model.chat').query('messages', {
      page: page
    }).then(function (response) {
      var array = self.get('messages');
      response.forEach(function(message) {
        array.push(message);
      });
    }
  }
```

**Comment by danilovaz** [comment]
@mdehoog It does not work :cry: . It seems that when I print `self.get( 'model.chat.chatMessages')` the array has already been updated with the response, so it already brings the 20 new items (deleting the 20 previous items).

I also could not (from my component) access: `this.get('model.chat')`, I had to do: `this.controller.get('model.chat')`.

Do you have any idea what might be happening to update the array before I can pick up the previous items?

**Comment by mdehoog** [comment]
`'model.chat.chatMessages'` will always contain the latest queried messages, because `'chat.chatMessages'` is the `hasMany` array. What you need to do is cache these messages in a separate array after every query is complete, and display this cached array instead of the has-many relationship.

**Comment by danilovaz** [comment]
Thank's @mdehoog I'll follow your tip.

**Comment by mhluska** [comment]
The issue with displaying the separate array instead of the canonical `hasMany` array is it makes subsequent operations tricky (like deleting items). Normally ember-data makes this stuff super simple as long as you stick to just using the canonical `hasMany` array.
