### ISSUE TITLE
Error about expecting DS.Snapshot instead of DS.Model

### ISSUE THREAD

**Issue by gnapse** [mdehoog/ember-data-has-many-query#18]
I'm getting this error when trying to invoke `.query` on a model with the mixin:

```
"Assertion Failed: The `hasMany` method is not available on DS.Model, a DS.Snapshot was probably expected. Are you passing a DS.Model instead of a DS.Snapshot to your serializer?"
```

The error occurs when trying to invoke `this.hasMany` in [this line](https://github.com/mdehoog/ember-data-has-many-query/blob/master/addon/mixins/model.js#L84).

Here are the steps I followed:

```Javascript
store.findRecord('structure', 123).then(structure => {
  structure.query('locations', { include: 'children' }).then(locations => {
    // I never get here
  });
});
```

The `structure.query` call breaks with the error message above.

**Comment by mdehoog** [comment]
Which version of Ember Data are you using? The `DS.Model.hasMany` method has been available since `2.5.0`: http://emberjs.com/api/data/classes/DS.Model.html#method_hasMany.

**Comment by gnapse** [comment]
Oh well, is there a workaround to use it in Ember 2.2.0 in the mean time? Unfortunately I'm on a project that has been heavily using deprecated stuff in 2.3 and we're in the process to clean up all that in order to upgrade Ember. If not possible never mind, we'll be able to use this after that upgrade is finished.

**Comment by mdehoog** [comment]
Try switching to version `0.0.6` of this addon in the meantime.

**Comment by gnapse** [comment]
Thanks, will do!
