### ISSUE TITLE
Mirage support

### ISSUE THREAD

**Issue by bttf** [mdehoog/ember-data-has-many-query#2]
Tried using the ModelMixin in a Mirage factory like so:

```
import Mirage from 'ember-cli-mirage';
import HasManyQuery from 'ember-data-has-many-query';

export default Mirage.Factory.extend(HasManyQuery.ModelMixin, {
  first_name() { return faker.name.firstName(); },
  last_name() { return faker.name.lastName(); },
  email() { return faker.internet.email(); },
});
```

Did not work to provide the `query` method we are using in our route: 

```
export default Ember.Route.extend({
  model(params) {
    const page = params.page;
    const limit = params.limit;
    const query = params.query;
    const userModel = this.modelFor('users.user');

    return Ember.RSVP.hash({
      user: userModel,
      requests: userModel.query('requests', { page: page, limit: limit, query: query }),
    });
  },
```

Ideally, `userModel.query` should make a request to `/users/:user_id/requests` but it is not making that request under Mirage generated models.

**Comment by mdehoog** [comment]
The ModelMixin is only designed for use with Ember Data models, and doesn't support Mirage factories.

**Comment by mupkoo** [comment]
@bttf you should do this in your route handler.

```javascript
this.get('/users', function (db, request) {
    let users = db.users;

    if (request.queryParams.page) {
        let offset = 10 * page;
        users = users.slice(offset, offset + 10);
    }

    return users;
});
```

Of course this is just an example. You need to implement the logic yourself.

**Comment by npendery** [comment]
@mdehoog is there any plan for Mirage support? Have you tried? If so, what are the blockers? Would be happy to help with this if there isnt a serious blocker that you stumbled upon
