### ISSUE TITLE
Usage with pagination

### ISSUE THREAD

**Issue by boyanyordanov** [mdehoog/ember-data-has-many-query#21]
Hello!

First of all, thank you for the work on this addon! 

Onto the question, I am using it on a model which has a relationship that matches a sub-resource on the api that is paginated.

I am making requests like this: 
```
item.query('sub-item', {page: 1})
item.query('sub-item', {page: 2})
```

Then I noticed a weird bug, where "sub-item" was losing its "item" relations, and traced it back to hasManyQuery. As far as I understand on each subsequent query it replaces the data currently in the relation with the new data.

For my pagination scenario to work properly it would need to append it instead.
I saw that a similar issue has been discussed in issue #1 but the solution proposed there is not appropriate for my case. 

Do you have any thoughts on this ?

I am able work on a PR if you think that something like that should go in the addon itself.

**Comment by mdehoog** [comment]
You will need to store the results from each query in a separate collection, and not make multiple queries at once. You can also use the `belongsToSticky` feature to ensure that each `sub-item`s `item` value is not cleared when the next query occurs.

**Comment by boyanyordanov** [comment]
I tried using `belongsToSticky` but I started seeing errors like this: 
```
Error: Assertion Failed: You cannot add a record of modelClass 'undefined' to the 'sub-item.items' relationship (only 'item' allowed)
```

The models look like this: 

```
Item = Model.extend(HasManyQuery.ModelMixin, {
  subItems: hasMany('sub-item')
});

SubItem = Model.extend({
  items: HasManyQuery.belongsToSticky('item')
});
```

Perhaps I am doing something wrong. And the relationship is actually many-to-many. Each item can have many sub-items and each sub-item can have many items. Basically categories. 

I think I can achieve this with manual request to the api and the feed the received data to the native hasMnay relation but I really like the simplicity of this addon.

**Comment by boyanyordanov** [comment]
Seems like our use case is not 100% compatible with the addon. I ended up implementing the approach for querying relationships described in this talk: https://youtu.be/kPxiiAGMSzE

Anyway thank you for your work on the addon and I'll keep an eye on it in future. 

I think the issue can be closed now.
