### ISSUE TITLE
Data is not reloaded if initial request returns no results

### ISSUE THREAD

**Issue by arschmitz** [mdehoog/ember-data-has-many-query#25]
If the first query for a model returns an empty set then one of the query params is changed the resource will not be reloaded and will continue to return an empty set.

**Comment by thedig** [comment]
hitting this same issue, any progress on incorporating the fix?

**Comment by thedig** [comment]
also checking out the fix's PR, looks like the wrong variable name (`forceReload` vs `force`) might be used in `reloadRelationship`, which might be causing the CI error:
https://github.com/mdehoog/ember-data-has-many-query/pull/26/files#diff-db478f9ef87f5a766fd804b373628213R89

```
    reloadRelationship: function (propertyName, forceReload) {
    ...
            if (isLoaded || force) {
```

**Comment by bryanhickerson** [comment]
I'm also hitting this issue. For now I'm going forking and run against @arschmitz's changes, but it would be great to get this merged in.

**Comment by adlius** [comment]
@arschmitz @thedig @bryanhickerson Hello guys. It seems that I am having similar issues. Did you guys encounter this bug only when initial query returns an empty set or whenever one query param is changed?

**Comment by bryanhickerson** [comment]
@adlius I only encountered it when the initial query returned an empty set. If the first request returned results, I got new results when changing the query params.

**Comment by arthur5005** [comment]
+1 on this. Only when initial query returns an empty set.

**Comment by arthur5005** [comment]
What's the hold up? How can we move this across the finish line.
