### ISSUE TITLE
Cannot read property 'get' of undefined TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by marat93** [mdehoog/ember-data-has-many-query#3]
I need to be able to do this
```javascript
model(params) {
    return this.get('session.currentUser').query('design', params);
}
```

So I added these lines:

app/adapters/application.js
```javascript
import DS from 'ember-data';
import ENV from '../config/environment';
import HasManyQuery from 'ember-data-has-many-query';

export default DS.JSONAPIAdapter.extend(HasManyQuery.RESTAdapterMixin, {
```

app/models/designer.js
```javascript
import Ember from 'ember';
import DS from 'ember-data';
import User from './user';
import HasManyQuery from 'ember-data-has-many-query';

export default User.extend(HasManyQuery.ModelMixin, {
  designs: DS.hasMany('design', { async: true }),
```

But ember shows me the following error:
![image](https://cloud.githubusercontent.com/assets/6310396/11331477/c447c0c0-91e5-11e5-8411-40c9b7377948.png)

Problem is in query method, because currentUser returns proper data:
![image](https://cloud.githubusercontent.com/assets/6310396/11331506/44dbc5ba-91e6-11e5-8c1b-22b4c386db1b.png)

**Comment by mdehoog** [comment]
Is `this.get('session.currentUser')` returning a promise? If so, does it work if you change it to the following?
```
model(params) {
    return this.get('session.currentUser').then(function(user) {
        return user.query('design', params);
    });
}
```

Alternatively, are you sure `session.currentUser` is available when the model hook is run? Ie:
```
model(params) {
    var currentUser = this.get('session.currentUser')
    console.log(currentUser);
    return currentUser.query('design', params);
}
```

**Comment by marat93** [comment]
Current user data stores in local storage so I think it could not be promise.

![image](https://cloud.githubusercontent.com/assets/6310396/11331819/d9afa442-91e9-11e5-87db-c4f2d8d6dcb9.png)

**Comment by mdehoog** [comment]
What happens if you do a `get` on the returned `currentUser` object? Is `get` undefined?
```
this.get('session.currentUser').get('someproperty');
```

**Comment by marat93** [comment]
Yeah, I can get any property on the returned `currentUser` object.

![image](https://cloud.githubusercontent.com/assets/6310396/11332835/27f71afa-91f3-11e5-93e2-0a151966cfa2.png)

**Comment by mdehoog** [comment]
Thanks for your help so far. Strange that `this` is undefined in `model.js` line 34, but line 31 (`this.set`) doesn't cause an error. Could you debug into the query method and do a `this` and `this.get('bio')` in the console?

Any chance of a jsbin that reproduces the issue?

**Comment by marat93** [comment]
I found a problem. I have been writing property name in singular form like in ember native [`query`] (http://guides.emberjs.com/v2.2.0/models/finding-records/#toc_querying-for-multiple-records) function, but it expect property names to be in plural form.
Following is the right version.
```javascript
model(params) {
    return this.get('session.currentUser').query('designs', params);
}
```

**Comment by mdehoog** [comment]
Yes the property name passed to `query` must match the `hasMany` property name.
