### ISSUE TITLE
Depending template not reloading

### ISSUE THREAD

**Issue by marat93** [mdehoog/ember-data-has-many-query#4]
I have the following route:
```javascript
import Ember from 'ember';

export default Ember.Route.extend({
  queryParams: {
    order: {
      refreshModel: true
    }
  },

  model(params) {
    return this.get('session.currentUser').query('design', params);
  }
});
```
and template
```javascript
{{#each model as |design| }}
  {{design.title}}
  {{design.description}}
{{/each}}
```

when `queryParams` change, model hook fires, new data fetch, but template doesn't rerender.

If I change model hook like this:
```javascript
model(params) {
  return this.store.query('design', params);
}
```

everything works fine, every time `queryParams` change, template rerenders.

**Comment by mdehoog** [comment]
If you step into the `query` function, is `value.reload()` being called on line 38?

**Comment by marat93** [comment]
Yeah, `value.reload()` is being called.
I can create jsbin which reproduce this behavior, but I don't know how to add this plugin to jsbin.

**Comment by mdehoog** [comment]
Sorry, hard to debug without being able to reproduce... https://ember-twiddle.com/ might be easier than jsbin. You can add this plugin by adding the individual files from https://github.com/mdehoog/ember-data-has-many-query/tree/master/addon (rename `index.js` to `has-many-query.js`), then import `has-many-query.js` where you want to use it.

**Comment by mdehoog** [comment]
Are you changing your `queryParams` via a `link-to` helper?

**Comment by marat93** [comment]
No, I change it manually in component.

**Comment by mdehoog** [comment]
Is it possible to provide a cut down example with your route/model/controller, and the component that changes the query param?

**Comment by marat93** [comment]
Sure, I am creating example on ember-twiddle.

**Comment by mdehoog** [comment]
Closing old issue.
