### ISSUE TITLE
Inconsistencies cf. Ember Data's .query

### ISSUE THREAD

**Issue by mwpastore** [mdehoog/ember-data-has-many-query#8]
First of all, thank you so much for this Ember Addon. It solves a huge use case for me! I will be sending  more people here as they start working with the json:api specification and corresponding Ember Data adapter.

I've noticed a few nitpicky inconsistencies between ember-data (ED) "native" and ember-data-has-many-query (HMQ) and thought it might be worth opening an issue to discuss them. First of all, ED `.query` takes a singular model name—even for hasMany relationships—whereas HMQ takes a plural model name. It's a little unfriendly to have to remember that it's `this.store.query('artist'` *singular* but `user.query('favorites'` *plural*, even though I'm expecting multiple records from both calls.

Secondly, it looks like ED escapes the query string but HMQ does not. For example, `GET /api/artists?filter%5Bfoo%5D=bar` *escaped* cf. `GET /api/user/me/favorites?filter[bar]=qux` *unescaped*. I don't know why ED does this but presumably it has something to do with security/safety. Would it make sense to align HMQ to ED's behavior?

Again, I recognize that these are nitpicky. Thank you in advance for your consideration.

**Comment by mdehoog** [comment]
Thanks for your comments.

With regards to the singular/plural properties, the plural property name simply matches the name of the `hasMany` relationship defined by the user. For ED, you are querying a model name, which is singular. In HMQ, you are querying an attribute/relationship on that model (`artist.favorites` in your example). Note that ED also uses the plural when calling `get` on the model (`artist.get('favorites');`). IMHO, it would be more confusing to have to use the singular name of the attribute for `query` and the plural for `get`.

You are correct in that square brackets should be encoded, I will fix that.

**Comment by mwpastore** [comment]
Ah, interesting. I hadn't thought about it that way. Anyway, thanks again, and thanks for the quick fix on the encoding!
