### ISSUE TITLE
Does this support defining a hasMany relationship with a property?

### ISSUE THREAD

**Issue by NullVoxPopuli** [mdehoog/ember-data-has-many-query#9]
like,
```
relationshipName: DS.belongsTo('modelName', { parent_model_id: this.get('id') }),
```
or something like that?

my issue right now is that when ember automatically retrieves an async relationship, it just calls the flat api, and I'd like a parameter to always be included that scopes the parent model's id. (Just so the user doesn't have free range to ALL of that resource)

**Comment by mdehoog** [comment]
It may be possible to use the `query` method to add parameters to an async belongsTo relationship (just like it does for the current hasMany implementation), by overriding the rest-adapters `findBelongsTo` in a similar way that this addon's rest-adapter mixin overrides `findHasMany`.

Using your example, you would use:
```javascript
entity.query('relationshipName', { parent_model_id: entity.get('id') });
```

Is this the kind of thing you are looking for? If so I'd be happy to implement something like this...

**Comment by NullVoxPopuli** [comment]
using a `query` definitely works. It's just, EmberData has no built in way to use the query params on a relationship. So, I think that's what I'm looking for.

For clarification:

Given that I have defined:

```
relationshipName: DS.belongsTo('modelName', { parent_model_id: this.get('id') }),
```
in the model, and call
```
myModel.relationshipName
```

it should be equivelant to

```
myModel.query('relationshipName', { parent_model_id: myModel.get('parentId') }
```

where `parentId` is an attribute on `myModel`, due to the belongsTo relationship.

**Comment by mdehoog** [comment]
I've made a change that allows you to define parameters in the model itself. The format is as follows:
```javascript
relationshipName: DS.belongsTo('modelName', { parameters: {
    constant_key: 'example_constant_value',
    parent_model_id: function() {
        return this.get('id');
    }
}})
```
Let me know how you go.
